version: 2

# Build documentation in the main branch
build:
  os: ubuntu-22.04
  tools:
    python: "3.9"
  apt_packages:
    - libblas-dev
    - liblapack-dev
    - gfortran

# Define the necessary Python dependencies
python:
  install:
    - requirements: requirements.txt
    - pip_install:
      - sphinx_rtd_theme

formats:
  - pdf
  - htmlzip
  - epub

# Build the documentation
sphinx:
  configuration: docs/source/conf.py