experiment:
  project_name: MF_TEST
  annotation_file: fake_regression_prediction_data.csv
  splits: MF_split.json
  balancing: category
  split_technique: k-fold
  epochs: 5
  batch_size: 32
  k: 3
  val_fraction: 0.1
  aggregation_level: slide
  with_continue: False
  task: regression

  evaluation:
    - balanced_accuracy
    - auc

  visualization:
    - learning_curve
    - confusion_matrix
    - roc_curve
    - layer_activations

datasets:
  - name: int_MF
    slide_path: ../../../Thom_Doeleman/CLAM_train_cropped
    tfrecord_path: int_MF/tfrecrods
    tile_path: int_MF/tiles
    used_for: training

  - name: ext_MF
    slide_path: ../../../Thom_Doeleman/CLAM_validate_cropped
    tfrecord_path: ext_MF/tfrecrods
    tile_path: ext_MF/tiles
    used_for: testing

benchmark_parameters:
  tile_px:
    - 256
  tile_um:
    - 20x
  normalization:
    - macenko
    - reinhard
#   - ruifrok
#   - cyclegan
  feature_extraction:
    - resnet50_imagenet
    - CTransPath
    #- transpath_mocov3
    #- RetCCL
    #- PLIP
    #- HistoSSL
    #- uni
    #- dino
    #- mocov2
    #- swav
    #- phikon
    #- gigapath
    #- barlow_twins
    - hibou_b
    #- pathoduet_ihc
    #- pathoduet_he
    #- kaiko_s8
    #- kaiko_s16
    #- kaiko_b8
    #- kaiko_b16
    #- kaiko_l14
    - h_optimus_0
    - virchow
    #- beph
  mil:
    #- CLAM_SB
    #- CLAM_MB
    - Attention_MIL
    #- transmil
    #- bistro.transformer
    - linear_mil
    #- mean_mil
    #- max_mil
    #- lse_mil
    #- lstm_mil
    #- deepset_mil
    #- distributionpooling_mil
    - varmil
